feat: usability test for ListUsers and ListGroups
cbs-software/smarteru-client pull request #15
Opened 2022-08-23 19:35 UTC by willsantanentcs

If approved, this PR will provide usability tests for the Client::listUsers and Client::listGroups methods, and update the Client so that the request body is formatted correctly.

2022-08-23 19:44 UTC, willsantanentcs commented on usability/ListGroupsLiveTest.php
> +$userKey = 'l!yv499vf^4^sd^5lnx18nzxhgi8ijx$6ytf4iur';
This was my user key earlier today, but I reset it before posting this.

2022-08-24 17:57 UTC, tomegantcs requested changes
I believe the `usability` directory should be renamed `example`.

2022-08-24 17:57 UTC, tomegantcs commented on usability/ListGroupsLiveTest.php
> +require('/../../data/ccp/smarteru-client/vendor/guzzlehttp/promises/src/Is.php');
Why not use

```php
require('../vendor/autoload.php');
```

First you get away with a single line of code. Second, it is the standard/expected code in a PHP library using `composer`. Third it makes this script independent of the location where someone has cloned the repository. I have it cloned to `C:\Users\Tom\Documents\SmarterU PHP Client Library` for instance so this script will not run for me as written.

2022-08-24 17:57 UTC, tomegantcs commented on usability/ListUsersLiveTest.php
> +require('/../../data/ccp/smarteru-client/vendor/guzzlehttp/promises/src/Is.php');
Why not use

```php
require('../vendor/autoload.php');
```

First you get away with a single line of code. Second, it is the standard/expected code in a PHP library using `composer`. Third it makes this script independent of the location where someone has cloned the repository. I have it cloned to `C:\Users\Tom\Documents\SmarterU PHP Client Library` for instance so this script will not run for me as written.

2022-08-24 17:57 UTC, tomegantcs commented on tests/Client/CreateGroupClientTest.php
> +        $body = str_replace('Package=', '', $body);
If the string `Package=` were to be in one of the request fields it would also be removed as written.

```suggestion
        $decodedBody = urldecode((string) $request->getBody());
        $body = strrpos($decodedBody, 'Package=') === 0 ? substr($decodedBody, 8, null) : '';
```

2022-08-24 17:57 UTC, tomegantcs commented on tests/Client/CreateGroupClientTest.php
> +        $body = str_replace('Package=', '', $body);
If the string `Package=` were to be in one of the request fields it would also be removed as written.

```suggestion
        $decodedBody = urldecode((string) $request->getBody());
        $body = strrpos($decodedBody, 'Package=') === 0 ? substr($decodedBody, 8, null) : '';
```

2022-08-24 17:57 UTC, tomegantcs commented on tests/Client/GetGroupClientTest.php
> +        $body = str_replace('Package=', '', $body);
If the string `Package=` were to be in one of the request fields it would also be removed as written.

```suggestion
        $decodedBody = urldecode((string) $request->getBody());
        $body = strrpos($decodedBody, 'Package=') === 0 ? substr($decodedBody, 8, null) : '';
```

2022-08-24 17:57 UTC, tomegantcs commented on tests/Client/GetGroupClientTest.php
> +        $body = str_replace('Package=', '', $body);
If the string `Package=` were to be in one of the request fields it would also be removed as written.

```suggestion
        $decodedBody = urldecode((string) $request->getBody());
        $body = strrpos($decodedBody, 'Package=') === 0 ? substr($decodedBody, 8, null) : '';
```

2022-08-24 17:57 UTC, tomegantcs commented on tests/Client/GetUserGroupsClientTest.php
> +        $body = str_replace('Package=', '', $body);
If the string `Package=` were to be in one of the request fields it would also be removed as written.

```suggestion
        $decodedBody = urldecode((string) $request->getBody());
        $body = strrpos($decodedBody, 'Package=') === 0 ? substr($decodedBody, 8, null) : '';
```

2022-08-24 17:57 UTC, tomegantcs commented on tests/Client/GetUserGroupsClientTest.php
> +        $body = str_replace('Package=', '', $body);
If the string `Package=` were to be in one of the request fields it would also be removed as written.

```suggestion
        $decodedBody = urldecode((string) $request->getBody());
        $body = strrpos($decodedBody, 'Package=') === 0 ? substr($decodedBody, 8, null) : '';
```

2022-08-24 17:57 UTC, tomegantcs commented on tests/Client/GetUserGroupsClientTest.php
> +        $body = str_replace('Package=', '', $body);
If the string `Package=` were to be in one of the request fields it would also be removed as written.

```suggestion
        $decodedBody = urldecode((string) $request->getBody());
        $body = strrpos($decodedBody, 'Package=') === 0 ? substr($decodedBody, 8, null) : '';
```

2022-08-24 17:57 UTC, tomegantcs commented on tests/Client/ListGroupsClientTest.php
> +        $body = str_replace('Package=', '', $body);
If the string `Package=` were to be in one of the request fields it would also be removed as written.

```suggestion
        $decodedBody = urldecode((string) $request->getBody());
        $body = strrpos($decodedBody, 'Package=') === 0 ? substr($decodedBody, 8, null) : '';
```

2022-08-24 17:57 UTC, tomegantcs commented on tests/Client/ListGroupsClientTest.php
> +        $body = str_replace('Package=', '', $body);
If the string `Package=` were to be in one of the request fields it would also be removed as written.

```suggestion
        $decodedBody = urldecode((string) $request->getBody());
        $body = strrpos($decodedBody, 'Package=') === 0 ? substr($decodedBody, 8, null) : '';
```

2022-08-24 17:57 UTC, tomegantcs commented on tests/Client/UpdateGroupClientTest.php
> +        $body = str_replace('Package=', '', $body);
If the string `Package=` were to be in one of the request fields it would also be removed as written.

```suggestion
        $decodedBody = urldecode((string) $request->getBody());
        $body = strrpos($decodedBody, 'Package=') === 0 ? substr($decodedBody, 8, null) : '';
```

2022-08-24 17:57 UTC, tomegantcs commented on tests/Client/UpdateGroupClientTest.php
> +        $body = str_replace('Package=', '', $body);
If the string `Package=` were to be in one of the request fields it would also be removed as written.

```suggestion
        $decodedBody = urldecode((string) $request->getBody());
        $body = strrpos($decodedBody, 'Package=') === 0 ? substr($decodedBody, 8, null) : '';
```

2022-08-24 17:57 UTC, tomegantcs commented on tests/ClientTest.php
> +        $body = str_replace('Package=', '', $body);
If the string `Package=` were to be in one of the request fields it would also be removed as written.

```suggestion
        $decodedBody = urldecode((string) $request->getBody());
        $body = strrpos($decodedBody, 'Package=') === 0 ? substr($decodedBody, 8, null) : '';
```

2022-08-24 17:57 UTC, tomegantcs commented on tests/ClientTest.php
> +        $body = str_replace('Package=', '', $body);
If the string `Package=` were to be in one of the request fields it would also be removed as written.

```suggestion
        $decodedBody = urldecode((string) $request->getBody());
        $body = strrpos($decodedBody, 'Package=') === 0 ? substr($decodedBody, 8, null) : '';
```

2022-08-24 17:57 UTC, tomegantcs commented on tests/ClientTest.php
> +        $body = str_replace('Package=', '', $body);
If the string `Package=` were to be in one of the request fields it would also be removed as written.

```suggestion
        $decodedBody = urldecode((string) $request->getBody());
        $body = strrpos($decodedBody, 'Package=') === 0 ? substr($decodedBody, 8, null) : '';
```

2022-08-24 17:57 UTC, tomegantcs commented on tests/ClientTest.php
> +        $body = str_replace('Package=', '', $body);
If the string `Package=` were to be in one of the request fields it would also be removed as written.

```suggestion
        $decodedBody = urldecode((string) $request->getBody());
        $body = strrpos($decodedBody, 'Package=') === 0 ? substr($decodedBody, 8, null) : '';
```

2022-08-24 17:57 UTC, tomegantcs commented on tests/ClientTest.php
> +        $body = str_replace('Package=', '', $body);
If the string `Package=` were to be in one of the request fields it would also be removed as written.

```suggestion
        $decodedBody = urldecode((string) $request->getBody());
        $body = strrpos($decodedBody, 'Package=') === 0 ? substr($decodedBody, 8, null) : '';
```

2022-08-24 17:57 UTC, tomegantcs commented on tests/ClientTest.php
> +        $body = str_replace('Package=', '', $body);
If the string `Package=` were to be in one of the request fields it would also be removed as written.

```suggestion
        $decodedBody = urldecode((string) $request->getBody());
        $body = strrpos($decodedBody, 'Package=') === 0 ? substr($decodedBody, 8, null) : '';
```

2022-08-24 17:57 UTC, tomegantcs commented on usability/ListGroupsLiveTest.php
> +Output as of 8/23/2022:
I appreciate the though here but you should not include actual output here. Instead provide example output containing anonymized data e.g. Company => Acme Corp, Name => Willie E Coyote, Phone => 1 000 867 5509. In general you do not want to every include verbatim output from running a script in code or even in PR comments as it risks giving away information about you, your organization etc that should not be made public. Should this repository be made public it would be scanned by bots looking for access tokens, passwords and identify details to be used against you and the organization.

2022-08-24 17:57 UTC, tomegantcs commented on usability/ListUsersLiveTest.php
> +Output as of 8/23/2022:
I appreciate the though here but you should not include actual output here. Instead provide example output containing anonymized data e.g. Company => Acme Corp, Name => Willie E Coyote, Phone => 1 000 867 5509. In general you do not want to every include verbatim output from running a script in code or even in PR comments as it risks giving away information about you, your organization etc that should not be made public. Should this repository be made public it would be scanned by bots looking for access tokens, passwords and identify details to be used against you and the organization.

2022-08-24 17:57 UTC, tomegantcs commented on usability/ListUsersLiveTest.php
> +}
Take a look at the C/PHP standard library [getopt](https://www.php.net/manual/en/function.getopt.php)

2022-08-24 17:57 UTC, tomegantcs commented on usability/ListGroupsLiveTest.php
> +$accountKey = ''; //insert key here before running
Commit 25554460b58b83a2586a77e67607f7f9110784b9 exposed our sandbox API key and we should squash this repository to remove all traces of that data exposure.

2022-08-24 17:57 UTC, tomegantcs commented on usability/ListUsersLiveTest.php
> +$accountKey = ''; //insert key here before running
Commit 2bd90e5c2f502c7433c2681706f440dfbcdaaae5 exposed our sandbox API key and we should squash this repository to remove all traces of that data exposure.

2022-08-24 20:52 UTC, brianreichtcs requested changes
Will,

This is my first serious look at the code and so I've got lots of comments that do not entirely line up with the lines changed in this PR.  So I'll put them here.

1. I think Tom already brought it up but we don't want to be split-brained about whether or not we're developing an object-oriented client.  Client methods should return objects as was written in the specification, not arrays.  If the API request is successful I'd expect the appropriate type for that API call to be returned (ex. `User`).  If an error is detected I would not expect the method to return anything; instead it should throw an `Exception` of a type appropriate to the error that was detected. Example of this issue: https://github.com/cbs-software/smarteru-client/blob/f746f63e3a10d0ba4ecc5e7d88cd7c736f059d15/src/Client.php#L167
2. You are looking at the response and doing error detection--that's good! But I see a lot of redundant error detection code in all your API methods.  Why not extract that out into a reusable function? Example: https://github.com/cbs-software/smarteru-client/blob/f746f63e3a10d0ba4ecc5e7d88cd7c736f059d15/src/Client.php#L196-L211
3. `createUser()` should return a `User`.  You can clone the one passed to the method, update it with any changes detected in the API response, and return it. Sort of like what we do with `create()` in most of our Models in CORE.
4. I would expect `getUser()` to return `?User`. Either a `User` instance if a match is found or null if not. If an error occurs, throw an Exception.
5. This block is almost identical at the top of every API wrapper method. It might be worth considering how you could define a reusable wrapper methods that covers all your bases and reduces code duplication. Would be better to think about this now before implementing lots of new API methods with lots of copy/paste code. https://github.com/cbs-software/smarteru-client/blob/f746f63e3a10d0ba4ecc5e7d88cd7c736f059d15/src/Client.php#L370-L384
6. `listUsers()` should return `User[]`.
7. `updateUser()` should return `User`.
8. `getUserGroups()` should return `Group[]`
9. `createGroup()` should return `Group`
10. `getGroup()` should return `?Group`
11. `listGroups()` should return `Group[]`
12. `updateGroup()` should return `Group`
13. I mentioned to Tom you might look at using  [parse_str()](https://www.php.net/manual/en/function.parse-str.php) for parsing the POST body back into something useful.  Its an option, but his way works too and I don't really care which you side on.

I've limited my review at this point to `Client`.  The changes I'd like to see in order to approve anything would be ensuring that all API methods return objects and not arrays; that they throw exceptions instead of returning error descriptor arrays or objects.

I won't demand it but I see a lot of opportunity for code simplification and reuse in that class already.  I'd be happy to think through some of that with you if you desire.  Take a look at the blocks of code that are almost identical between these methods and do a little pattern matching. What's the thing that's different? Can you factor that code out into a parameterized method that can be called with just the input that differs between versions of that code block?

2022-08-24 21:02 UTC, brianreichtcs commented on usability/ListGroupsLiveTest.php
> +require('/../../data/ccp/smarteru-client/vendor/guzzlehttp/promises/src/Is.php');
+1 Tom's comment.  If you find yourself using `require()` in PHP code these days, stop and ask yourself why.  The autoloader is your friend.  Either composer.json is not setup with the right PSR-4 autoloading setup, or PHPUnit is not setup to load `vendor/autoload.php` as a bootstrapping step.

2022-08-25 19:03 UTC, willsantanentcs commented on example/UpdateUserLiveTest.php
> +<?php
I wrote this because I wanted to see how the API handles things that I assumed would be non-fatal errors. The documentation provided isn't very clear in this regard. Based on my testing with several different optional attributes, it appears that all errors are fatal.

2022-08-29 14:27 UTC, tomegantcs approved these changes

2022-08-29 14:27 UTC, tomegantcs commented on example/ListGroupsLiveTest.php
> +
This is better. One idea for the future would be a check that prints a little message about providing the keys if the script is run without providing them.

2022-08-29 14:27 UTC, tomegantcs commented on example/UpdateUserLiveTest.php
> +<?php
👍

2022-08-29 19:03 UTC, brianreichtcs approved these changes
Approved given the limited scope of what was expected to be achieved in the PR.

2022-08-29 19:04 UTC, merged